//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_giayit.ServiceReferenceChiTietPhieuNhap {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="chitietphieunhap", Namespace="http://schemas.datacontract.org/2004/07/ServiceGiayit")]
    [System.SerializableAttribute()]
    public partial class chitietphieunhap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> giaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int maphieunhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string masanphamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QL_giayit.ServiceReferenceChiTietPhieuNhap.phieunhap phieunhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QL_giayit.ServiceReferenceChiTietPhieuNhap.sanpham sanphamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int soluongField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> gia {
            get {
                return this.giaField;
            }
            set {
                if ((this.giaField.Equals(value) != true)) {
                    this.giaField = value;
                    this.RaisePropertyChanged("gia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int maphieunhap {
            get {
                return this.maphieunhapField;
            }
            set {
                if ((this.maphieunhapField.Equals(value) != true)) {
                    this.maphieunhapField = value;
                    this.RaisePropertyChanged("maphieunhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string masanpham {
            get {
                return this.masanphamField;
            }
            set {
                if ((object.ReferenceEquals(this.masanphamField, value) != true)) {
                    this.masanphamField = value;
                    this.RaisePropertyChanged("masanpham");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QL_giayit.ServiceReferenceChiTietPhieuNhap.phieunhap phieunhap {
            get {
                return this.phieunhapField;
            }
            set {
                if ((object.ReferenceEquals(this.phieunhapField, value) != true)) {
                    this.phieunhapField = value;
                    this.RaisePropertyChanged("phieunhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QL_giayit.ServiceReferenceChiTietPhieuNhap.sanpham sanpham {
            get {
                return this.sanphamField;
            }
            set {
                if ((object.ReferenceEquals(this.sanphamField, value) != true)) {
                    this.sanphamField = value;
                    this.RaisePropertyChanged("sanpham");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int soluong {
            get {
                return this.soluongField;
            }
            set {
                if ((this.soluongField.Equals(value) != true)) {
                    this.soluongField = value;
                    this.RaisePropertyChanged("soluong");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="phieunhap", Namespace="http://schemas.datacontract.org/2004/07/ServiceGiayit")]
    [System.SerializableAttribute()]
    public partial class phieunhap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QL_giayit.ServiceReferenceChiTietPhieuNhap.chitietphieunhap[] chitietphieunhapsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int maphieunhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ngaynhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nguoinhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> tongtienField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QL_giayit.ServiceReferenceChiTietPhieuNhap.chitietphieunhap[] chitietphieunhaps {
            get {
                return this.chitietphieunhapsField;
            }
            set {
                if ((object.ReferenceEquals(this.chitietphieunhapsField, value) != true)) {
                    this.chitietphieunhapsField = value;
                    this.RaisePropertyChanged("chitietphieunhaps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int maphieunhap {
            get {
                return this.maphieunhapField;
            }
            set {
                if ((this.maphieunhapField.Equals(value) != true)) {
                    this.maphieunhapField = value;
                    this.RaisePropertyChanged("maphieunhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ngaynhap {
            get {
                return this.ngaynhapField;
            }
            set {
                if ((this.ngaynhapField.Equals(value) != true)) {
                    this.ngaynhapField = value;
                    this.RaisePropertyChanged("ngaynhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nguoinhap {
            get {
                return this.nguoinhapField;
            }
            set {
                if ((object.ReferenceEquals(this.nguoinhapField, value) != true)) {
                    this.nguoinhapField = value;
                    this.RaisePropertyChanged("nguoinhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> tongtien {
            get {
                return this.tongtienField;
            }
            set {
                if ((this.tongtienField.Equals(value) != true)) {
                    this.tongtienField = value;
                    this.RaisePropertyChanged("tongtien");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="sanpham", Namespace="http://schemas.datacontract.org/2004/07/ServiceGiayit")]
    [System.SerializableAttribute()]
    public partial class sanpham : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string chatlieuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QL_giayit.ServiceReferenceChiTietPhieuNhap.chitiethoadon[] chitiethoadonsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QL_giayit.ServiceReferenceChiTietPhieuNhap.chitietphieunhap[] chitietphieunhapsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ghichuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int giasanphamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string hinhanhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QL_giayit.ServiceReferenceChiTietPhieuNhap.loaisanpham loaisanphamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maloaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> manhacungcapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string masanphamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string motasanphamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QL_giayit.ServiceReferenceChiTietPhieuNhap.nhacungcap nhacungcapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sanphammoiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int soluongconField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sttField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tensanphamField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string chatlieu {
            get {
                return this.chatlieuField;
            }
            set {
                if ((object.ReferenceEquals(this.chatlieuField, value) != true)) {
                    this.chatlieuField = value;
                    this.RaisePropertyChanged("chatlieu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QL_giayit.ServiceReferenceChiTietPhieuNhap.chitiethoadon[] chitiethoadons {
            get {
                return this.chitiethoadonsField;
            }
            set {
                if ((object.ReferenceEquals(this.chitiethoadonsField, value) != true)) {
                    this.chitiethoadonsField = value;
                    this.RaisePropertyChanged("chitiethoadons");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QL_giayit.ServiceReferenceChiTietPhieuNhap.chitietphieunhap[] chitietphieunhaps {
            get {
                return this.chitietphieunhapsField;
            }
            set {
                if ((object.ReferenceEquals(this.chitietphieunhapsField, value) != true)) {
                    this.chitietphieunhapsField = value;
                    this.RaisePropertyChanged("chitietphieunhaps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ghichu {
            get {
                return this.ghichuField;
            }
            set {
                if ((this.ghichuField.Equals(value) != true)) {
                    this.ghichuField = value;
                    this.RaisePropertyChanged("ghichu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int giasanpham {
            get {
                return this.giasanphamField;
            }
            set {
                if ((this.giasanphamField.Equals(value) != true)) {
                    this.giasanphamField = value;
                    this.RaisePropertyChanged("giasanpham");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string hinhanh {
            get {
                return this.hinhanhField;
            }
            set {
                if ((object.ReferenceEquals(this.hinhanhField, value) != true)) {
                    this.hinhanhField = value;
                    this.RaisePropertyChanged("hinhanh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QL_giayit.ServiceReferenceChiTietPhieuNhap.loaisanpham loaisanpham {
            get {
                return this.loaisanphamField;
            }
            set {
                if ((object.ReferenceEquals(this.loaisanphamField, value) != true)) {
                    this.loaisanphamField = value;
                    this.RaisePropertyChanged("loaisanpham");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maloai {
            get {
                return this.maloaiField;
            }
            set {
                if ((object.ReferenceEquals(this.maloaiField, value) != true)) {
                    this.maloaiField = value;
                    this.RaisePropertyChanged("maloai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> manhacungcap {
            get {
                return this.manhacungcapField;
            }
            set {
                if ((this.manhacungcapField.Equals(value) != true)) {
                    this.manhacungcapField = value;
                    this.RaisePropertyChanged("manhacungcap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string masanpham {
            get {
                return this.masanphamField;
            }
            set {
                if ((object.ReferenceEquals(this.masanphamField, value) != true)) {
                    this.masanphamField = value;
                    this.RaisePropertyChanged("masanpham");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string motasanpham {
            get {
                return this.motasanphamField;
            }
            set {
                if ((object.ReferenceEquals(this.motasanphamField, value) != true)) {
                    this.motasanphamField = value;
                    this.RaisePropertyChanged("motasanpham");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QL_giayit.ServiceReferenceChiTietPhieuNhap.nhacungcap nhacungcap {
            get {
                return this.nhacungcapField;
            }
            set {
                if ((object.ReferenceEquals(this.nhacungcapField, value) != true)) {
                    this.nhacungcapField = value;
                    this.RaisePropertyChanged("nhacungcap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int sanphammoi {
            get {
                return this.sanphammoiField;
            }
            set {
                if ((this.sanphammoiField.Equals(value) != true)) {
                    this.sanphammoiField = value;
                    this.RaisePropertyChanged("sanphammoi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int soluongcon {
            get {
                return this.soluongconField;
            }
            set {
                if ((this.soluongconField.Equals(value) != true)) {
                    this.soluongconField = value;
                    this.RaisePropertyChanged("soluongcon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int stt {
            get {
                return this.sttField;
            }
            set {
                if ((this.sttField.Equals(value) != true)) {
                    this.sttField = value;
                    this.RaisePropertyChanged("stt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tensanpham {
            get {
                return this.tensanphamField;
            }
            set {
                if ((object.ReferenceEquals(this.tensanphamField, value) != true)) {
                    this.tensanphamField = value;
                    this.RaisePropertyChanged("tensanpham");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="loaisanpham", Namespace="http://schemas.datacontract.org/2004/07/ServiceGiayit")]
    [System.SerializableAttribute()]
    public partial class loaisanpham : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maloaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QL_giayit.ServiceReferenceChiTietPhieuNhap.sanpham[] sanphamsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tenloaiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maloai {
            get {
                return this.maloaiField;
            }
            set {
                if ((object.ReferenceEquals(this.maloaiField, value) != true)) {
                    this.maloaiField = value;
                    this.RaisePropertyChanged("maloai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QL_giayit.ServiceReferenceChiTietPhieuNhap.sanpham[] sanphams {
            get {
                return this.sanphamsField;
            }
            set {
                if ((object.ReferenceEquals(this.sanphamsField, value) != true)) {
                    this.sanphamsField = value;
                    this.RaisePropertyChanged("sanphams");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tenloai {
            get {
                return this.tenloaiField;
            }
            set {
                if ((object.ReferenceEquals(this.tenloaiField, value) != true)) {
                    this.tenloaiField = value;
                    this.RaisePropertyChanged("tenloai");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="nhacungcap", Namespace="http://schemas.datacontract.org/2004/07/ServiceGiayit")]
    [System.SerializableAttribute()]
    public partial class nhacungcap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string diachiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int manhacungcapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QL_giayit.ServiceReferenceChiTietPhieuNhap.sanpham[] sanphamsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sdtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tennhacungcapField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string diachi {
            get {
                return this.diachiField;
            }
            set {
                if ((object.ReferenceEquals(this.diachiField, value) != true)) {
                    this.diachiField = value;
                    this.RaisePropertyChanged("diachi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int manhacungcap {
            get {
                return this.manhacungcapField;
            }
            set {
                if ((this.manhacungcapField.Equals(value) != true)) {
                    this.manhacungcapField = value;
                    this.RaisePropertyChanged("manhacungcap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QL_giayit.ServiceReferenceChiTietPhieuNhap.sanpham[] sanphams {
            get {
                return this.sanphamsField;
            }
            set {
                if ((object.ReferenceEquals(this.sanphamsField, value) != true)) {
                    this.sanphamsField = value;
                    this.RaisePropertyChanged("sanphams");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sdt {
            get {
                return this.sdtField;
            }
            set {
                if ((object.ReferenceEquals(this.sdtField, value) != true)) {
                    this.sdtField = value;
                    this.RaisePropertyChanged("sdt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tennhacungcap {
            get {
                return this.tennhacungcapField;
            }
            set {
                if ((object.ReferenceEquals(this.tennhacungcapField, value) != true)) {
                    this.tennhacungcapField = value;
                    this.RaisePropertyChanged("tennhacungcap");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="chitiethoadon", Namespace="http://schemas.datacontract.org/2004/07/ServiceGiayit")]
    [System.SerializableAttribute()]
    public partial class chitiethoadon : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> giasanphamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QL_giayit.ServiceReferenceChiTietPhieuNhap.hoadon hoadonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int mahoadonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string masanphamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QL_giayit.ServiceReferenceChiTietPhieuNhap.sanpham sanphamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> soluongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tensanphamField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> giasanpham {
            get {
                return this.giasanphamField;
            }
            set {
                if ((this.giasanphamField.Equals(value) != true)) {
                    this.giasanphamField = value;
                    this.RaisePropertyChanged("giasanpham");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QL_giayit.ServiceReferenceChiTietPhieuNhap.hoadon hoadon {
            get {
                return this.hoadonField;
            }
            set {
                if ((object.ReferenceEquals(this.hoadonField, value) != true)) {
                    this.hoadonField = value;
                    this.RaisePropertyChanged("hoadon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int mahoadon {
            get {
                return this.mahoadonField;
            }
            set {
                if ((this.mahoadonField.Equals(value) != true)) {
                    this.mahoadonField = value;
                    this.RaisePropertyChanged("mahoadon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string masanpham {
            get {
                return this.masanphamField;
            }
            set {
                if ((object.ReferenceEquals(this.masanphamField, value) != true)) {
                    this.masanphamField = value;
                    this.RaisePropertyChanged("masanpham");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QL_giayit.ServiceReferenceChiTietPhieuNhap.sanpham sanpham {
            get {
                return this.sanphamField;
            }
            set {
                if ((object.ReferenceEquals(this.sanphamField, value) != true)) {
                    this.sanphamField = value;
                    this.RaisePropertyChanged("sanpham");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> soluong {
            get {
                return this.soluongField;
            }
            set {
                if ((this.soluongField.Equals(value) != true)) {
                    this.soluongField = value;
                    this.RaisePropertyChanged("soluong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tensanpham {
            get {
                return this.tensanphamField;
            }
            set {
                if ((object.ReferenceEquals(this.tensanphamField, value) != true)) {
                    this.tensanphamField = value;
                    this.RaisePropertyChanged("tensanpham");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="hoadon", Namespace="http://schemas.datacontract.org/2004/07/ServiceGiayit")]
    [System.SerializableAttribute()]
    public partial class hoadon : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QL_giayit.ServiceReferenceChiTietPhieuNhap.chitiethoadon[] chitiethoadonsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string diachiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ghichuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int mahoadonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string makhachhangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ngaygiaohangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ngaymuahangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sdtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tenkhachhangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tinhtrangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> tongtienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QL_giayit.ServiceReferenceChiTietPhieuNhap.user userField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QL_giayit.ServiceReferenceChiTietPhieuNhap.chitiethoadon[] chitiethoadons {
            get {
                return this.chitiethoadonsField;
            }
            set {
                if ((object.ReferenceEquals(this.chitiethoadonsField, value) != true)) {
                    this.chitiethoadonsField = value;
                    this.RaisePropertyChanged("chitiethoadons");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string diachi {
            get {
                return this.diachiField;
            }
            set {
                if ((object.ReferenceEquals(this.diachiField, value) != true)) {
                    this.diachiField = value;
                    this.RaisePropertyChanged("diachi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ghichu {
            get {
                return this.ghichuField;
            }
            set {
                if ((object.ReferenceEquals(this.ghichuField, value) != true)) {
                    this.ghichuField = value;
                    this.RaisePropertyChanged("ghichu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int mahoadon {
            get {
                return this.mahoadonField;
            }
            set {
                if ((this.mahoadonField.Equals(value) != true)) {
                    this.mahoadonField = value;
                    this.RaisePropertyChanged("mahoadon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string makhachhang {
            get {
                return this.makhachhangField;
            }
            set {
                if ((object.ReferenceEquals(this.makhachhangField, value) != true)) {
                    this.makhachhangField = value;
                    this.RaisePropertyChanged("makhachhang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ngaygiaohang {
            get {
                return this.ngaygiaohangField;
            }
            set {
                if ((this.ngaygiaohangField.Equals(value) != true)) {
                    this.ngaygiaohangField = value;
                    this.RaisePropertyChanged("ngaygiaohang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ngaymuahang {
            get {
                return this.ngaymuahangField;
            }
            set {
                if ((this.ngaymuahangField.Equals(value) != true)) {
                    this.ngaymuahangField = value;
                    this.RaisePropertyChanged("ngaymuahang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sdt {
            get {
                return this.sdtField;
            }
            set {
                if ((object.ReferenceEquals(this.sdtField, value) != true)) {
                    this.sdtField = value;
                    this.RaisePropertyChanged("sdt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tenkhachhang {
            get {
                return this.tenkhachhangField;
            }
            set {
                if ((object.ReferenceEquals(this.tenkhachhangField, value) != true)) {
                    this.tenkhachhangField = value;
                    this.RaisePropertyChanged("tenkhachhang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tinhtrang {
            get {
                return this.tinhtrangField;
            }
            set {
                if ((object.ReferenceEquals(this.tinhtrangField, value) != true)) {
                    this.tinhtrangField = value;
                    this.RaisePropertyChanged("tinhtrang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> tongtien {
            get {
                return this.tongtienField;
            }
            set {
                if ((this.tongtienField.Equals(value) != true)) {
                    this.tongtienField = value;
                    this.RaisePropertyChanged("tongtien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QL_giayit.ServiceReferenceChiTietPhieuNhap.user user {
            get {
                return this.userField;
            }
            set {
                if ((object.ReferenceEquals(this.userField, value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="user", Namespace="http://schemas.datacontract.org/2004/07/ServiceGiayit")]
    [System.SerializableAttribute()]
    public partial class user : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string diachiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ghichuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> gioitinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QL_giayit.ServiceReferenceChiTietPhieuNhap.hoadon[] hoadonsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string makhachhangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> maphanquyenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ngaysinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QL_giayit.ServiceReferenceChiTietPhieuNhap.phanquyen phanquyenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sdtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tenkhachhangField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string diachi {
            get {
                return this.diachiField;
            }
            set {
                if ((object.ReferenceEquals(this.diachiField, value) != true)) {
                    this.diachiField = value;
                    this.RaisePropertyChanged("diachi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ghichu {
            get {
                return this.ghichuField;
            }
            set {
                if ((object.ReferenceEquals(this.ghichuField, value) != true)) {
                    this.ghichuField = value;
                    this.RaisePropertyChanged("ghichu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> gioitinh {
            get {
                return this.gioitinhField;
            }
            set {
                if ((this.gioitinhField.Equals(value) != true)) {
                    this.gioitinhField = value;
                    this.RaisePropertyChanged("gioitinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QL_giayit.ServiceReferenceChiTietPhieuNhap.hoadon[] hoadons {
            get {
                return this.hoadonsField;
            }
            set {
                if ((object.ReferenceEquals(this.hoadonsField, value) != true)) {
                    this.hoadonsField = value;
                    this.RaisePropertyChanged("hoadons");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string makhachhang {
            get {
                return this.makhachhangField;
            }
            set {
                if ((object.ReferenceEquals(this.makhachhangField, value) != true)) {
                    this.makhachhangField = value;
                    this.RaisePropertyChanged("makhachhang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> maphanquyen {
            get {
                return this.maphanquyenField;
            }
            set {
                if ((this.maphanquyenField.Equals(value) != true)) {
                    this.maphanquyenField = value;
                    this.RaisePropertyChanged("maphanquyen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ngaysinh {
            get {
                return this.ngaysinhField;
            }
            set {
                if ((this.ngaysinhField.Equals(value) != true)) {
                    this.ngaysinhField = value;
                    this.RaisePropertyChanged("ngaysinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QL_giayit.ServiceReferenceChiTietPhieuNhap.phanquyen phanquyen {
            get {
                return this.phanquyenField;
            }
            set {
                if ((object.ReferenceEquals(this.phanquyenField, value) != true)) {
                    this.phanquyenField = value;
                    this.RaisePropertyChanged("phanquyen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sdt {
            get {
                return this.sdtField;
            }
            set {
                if ((object.ReferenceEquals(this.sdtField, value) != true)) {
                    this.sdtField = value;
                    this.RaisePropertyChanged("sdt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tenkhachhang {
            get {
                return this.tenkhachhangField;
            }
            set {
                if ((object.ReferenceEquals(this.tenkhachhangField, value) != true)) {
                    this.tenkhachhangField = value;
                    this.RaisePropertyChanged("tenkhachhang");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="phanquyen", Namespace="http://schemas.datacontract.org/2004/07/ServiceGiayit")]
    [System.SerializableAttribute()]
    public partial class phanquyen : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int maphanquyenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string quyenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QL_giayit.ServiceReferenceChiTietPhieuNhap.user[] usersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int maphanquyen {
            get {
                return this.maphanquyenField;
            }
            set {
                if ((this.maphanquyenField.Equals(value) != true)) {
                    this.maphanquyenField = value;
                    this.RaisePropertyChanged("maphanquyen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string quyen {
            get {
                return this.quyenField;
            }
            set {
                if ((object.ReferenceEquals(this.quyenField, value) != true)) {
                    this.quyenField = value;
                    this.RaisePropertyChanged("quyen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QL_giayit.ServiceReferenceChiTietPhieuNhap.user[] users {
            get {
                return this.usersField;
            }
            set {
                if ((object.ReferenceEquals(this.usersField, value) != true)) {
                    this.usersField = value;
                    this.RaisePropertyChanged("users");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceChiTietPhieuNhap.IServiceChiTietPhieuNhap")]
    public interface IServiceChiTietPhieuNhap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietPhieuNhap/getallchitietphieunhap", ReplyAction="http://tempuri.org/IServiceChiTietPhieuNhap/getallchitietphieunhapResponse")]
        QL_giayit.ServiceReferenceChiTietPhieuNhap.chitietphieunhap[] getallchitietphieunhap();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietPhieuNhap/getallchitietphieunhap", ReplyAction="http://tempuri.org/IServiceChiTietPhieuNhap/getallchitietphieunhapResponse")]
        System.Threading.Tasks.Task<QL_giayit.ServiceReferenceChiTietPhieuNhap.chitietphieunhap[]> getallchitietphieunhapAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietPhieuNhap/Select_chitietphieunhap_theonam", ReplyAction="http://tempuri.org/IServiceChiTietPhieuNhap/Select_chitietphieunhap_theonamRespon" +
            "se")]
        QL_giayit.ServiceReferenceChiTietPhieuNhap.chitietphieunhap[] Select_chitietphieunhap_theonam(int nam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietPhieuNhap/Select_chitietphieunhap_theonam", ReplyAction="http://tempuri.org/IServiceChiTietPhieuNhap/Select_chitietphieunhap_theonamRespon" +
            "se")]
        System.Threading.Tasks.Task<QL_giayit.ServiceReferenceChiTietPhieuNhap.chitietphieunhap[]> Select_chitietphieunhap_theonamAsync(int nam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietPhieuNhap/laysoluongtheothang", ReplyAction="http://tempuri.org/IServiceChiTietPhieuNhap/laysoluongtheothangResponse")]
        int laysoluongtheothang(int thang, QL_giayit.ServiceReferenceChiTietPhieuNhap.chitietphieunhap[] dsctpn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietPhieuNhap/laysoluongtheothang", ReplyAction="http://tempuri.org/IServiceChiTietPhieuNhap/laysoluongtheothangResponse")]
        System.Threading.Tasks.Task<int> laysoluongtheothangAsync(int thang, QL_giayit.ServiceReferenceChiTietPhieuNhap.chitietphieunhap[] dsctpn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietPhieuNhap/Select_chitietphieunhap_theothang", ReplyAction="http://tempuri.org/IServiceChiTietPhieuNhap/Select_chitietphieunhap_theothangResp" +
            "onse")]
        QL_giayit.ServiceReferenceChiTietPhieuNhap.chitietphieunhap[] Select_chitietphieunhap_theothang(int thang, int nam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietPhieuNhap/Select_chitietphieunhap_theothang", ReplyAction="http://tempuri.org/IServiceChiTietPhieuNhap/Select_chitietphieunhap_theothangResp" +
            "onse")]
        System.Threading.Tasks.Task<QL_giayit.ServiceReferenceChiTietPhieuNhap.chitietphieunhap[]> Select_chitietphieunhap_theothangAsync(int thang, int nam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietPhieuNhap/laysoluongtheongay", ReplyAction="http://tempuri.org/IServiceChiTietPhieuNhap/laysoluongtheongayResponse")]
        int laysoluongtheongay(int ngay, QL_giayit.ServiceReferenceChiTietPhieuNhap.chitietphieunhap[] dsctpn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietPhieuNhap/laysoluongtheongay", ReplyAction="http://tempuri.org/IServiceChiTietPhieuNhap/laysoluongtheongayResponse")]
        System.Threading.Tasks.Task<int> laysoluongtheongayAsync(int ngay, QL_giayit.ServiceReferenceChiTietPhieuNhap.chitietphieunhap[] dsctpn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietPhieuNhap/Themctpn", ReplyAction="http://tempuri.org/IServiceChiTietPhieuNhap/ThemctpnResponse")]
        bool Themctpn(int maphieunhap, string masanpham, int gia, int soluong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietPhieuNhap/Themctpn", ReplyAction="http://tempuri.org/IServiceChiTietPhieuNhap/ThemctpnResponse")]
        System.Threading.Tasks.Task<bool> ThemctpnAsync(int maphieunhap, string masanpham, int gia, int soluong);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChiTietPhieuNhapChannel : QL_giayit.ServiceReferenceChiTietPhieuNhap.IServiceChiTietPhieuNhap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceChiTietPhieuNhapClient : System.ServiceModel.ClientBase<QL_giayit.ServiceReferenceChiTietPhieuNhap.IServiceChiTietPhieuNhap>, QL_giayit.ServiceReferenceChiTietPhieuNhap.IServiceChiTietPhieuNhap {
        
        public ServiceChiTietPhieuNhapClient() {
        }
        
        public ServiceChiTietPhieuNhapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceChiTietPhieuNhapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceChiTietPhieuNhapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceChiTietPhieuNhapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public QL_giayit.ServiceReferenceChiTietPhieuNhap.chitietphieunhap[] getallchitietphieunhap() {
            return base.Channel.getallchitietphieunhap();
        }
        
        public System.Threading.Tasks.Task<QL_giayit.ServiceReferenceChiTietPhieuNhap.chitietphieunhap[]> getallchitietphieunhapAsync() {
            return base.Channel.getallchitietphieunhapAsync();
        }
        
        public QL_giayit.ServiceReferenceChiTietPhieuNhap.chitietphieunhap[] Select_chitietphieunhap_theonam(int nam) {
            return base.Channel.Select_chitietphieunhap_theonam(nam);
        }
        
        public System.Threading.Tasks.Task<QL_giayit.ServiceReferenceChiTietPhieuNhap.chitietphieunhap[]> Select_chitietphieunhap_theonamAsync(int nam) {
            return base.Channel.Select_chitietphieunhap_theonamAsync(nam);
        }
        
        public int laysoluongtheothang(int thang, QL_giayit.ServiceReferenceChiTietPhieuNhap.chitietphieunhap[] dsctpn) {
            return base.Channel.laysoluongtheothang(thang, dsctpn);
        }
        
        public System.Threading.Tasks.Task<int> laysoluongtheothangAsync(int thang, QL_giayit.ServiceReferenceChiTietPhieuNhap.chitietphieunhap[] dsctpn) {
            return base.Channel.laysoluongtheothangAsync(thang, dsctpn);
        }
        
        public QL_giayit.ServiceReferenceChiTietPhieuNhap.chitietphieunhap[] Select_chitietphieunhap_theothang(int thang, int nam) {
            return base.Channel.Select_chitietphieunhap_theothang(thang, nam);
        }
        
        public System.Threading.Tasks.Task<QL_giayit.ServiceReferenceChiTietPhieuNhap.chitietphieunhap[]> Select_chitietphieunhap_theothangAsync(int thang, int nam) {
            return base.Channel.Select_chitietphieunhap_theothangAsync(thang, nam);
        }
        
        public int laysoluongtheongay(int ngay, QL_giayit.ServiceReferenceChiTietPhieuNhap.chitietphieunhap[] dsctpn) {
            return base.Channel.laysoluongtheongay(ngay, dsctpn);
        }
        
        public System.Threading.Tasks.Task<int> laysoluongtheongayAsync(int ngay, QL_giayit.ServiceReferenceChiTietPhieuNhap.chitietphieunhap[] dsctpn) {
            return base.Channel.laysoluongtheongayAsync(ngay, dsctpn);
        }
        
        public bool Themctpn(int maphieunhap, string masanpham, int gia, int soluong) {
            return base.Channel.Themctpn(maphieunhap, masanpham, gia, soluong);
        }
        
        public System.Threading.Tasks.Task<bool> ThemctpnAsync(int maphieunhap, string masanpham, int gia, int soluong) {
            return base.Channel.ThemctpnAsync(maphieunhap, masanpham, gia, soluong);
        }
    }
}
