//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace giayit.ServiceReferenceTonKho {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tonkho", Namespace="http://schemas.datacontract.org/2004/07/ServiceGiayit")]
    [System.SerializableAttribute()]
    public partial class tonkho : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string masanphamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ngayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> soluongField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string masanpham {
            get {
                return this.masanphamField;
            }
            set {
                if ((object.ReferenceEquals(this.masanphamField, value) != true)) {
                    this.masanphamField = value;
                    this.RaisePropertyChanged("masanpham");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ngay {
            get {
                return this.ngayField;
            }
            set {
                if ((this.ngayField.Equals(value) != true)) {
                    this.ngayField = value;
                    this.RaisePropertyChanged("ngay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> soluong {
            get {
                return this.soluongField;
            }
            set {
                if ((this.soluongField.Equals(value) != true)) {
                    this.soluongField = value;
                    this.RaisePropertyChanged("soluong");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceTonKho.IServiceTonKho")]
    public interface IServiceTonKho {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTonKho/getalltonkho", ReplyAction="http://tempuri.org/IServiceTonKho/getalltonkhoResponse")]
        giayit.ServiceReferenceTonKho.tonkho[] getalltonkho();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTonKho/getalltonkho", ReplyAction="http://tempuri.org/IServiceTonKho/getalltonkhoResponse")]
        System.Threading.Tasks.Task<giayit.ServiceReferenceTonKho.tonkho[]> getalltonkhoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTonKho/getalltonkholoc", ReplyAction="http://tempuri.org/IServiceTonKho/getalltonkholocResponse")]
        giayit.ServiceReferenceTonKho.tonkho[] getalltonkholoc(System.DateTime time);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTonKho/getalltonkholoc", ReplyAction="http://tempuri.org/IServiceTonKho/getalltonkholocResponse")]
        System.Threading.Tasks.Task<giayit.ServiceReferenceTonKho.tonkho[]> getalltonkholocAsync(System.DateTime time);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTonKho/Select_tonkho", ReplyAction="http://tempuri.org/IServiceTonKho/Select_tonkhoResponse")]
        giayit.ServiceReferenceTonKho.tonkho[] Select_tonkho(System.DateTime ngay, string maloai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTonKho/Select_tonkho", ReplyAction="http://tempuri.org/IServiceTonKho/Select_tonkhoResponse")]
        System.Threading.Tasks.Task<giayit.ServiceReferenceTonKho.tonkho[]> Select_tonkhoAsync(System.DateTime ngay, string maloai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTonKho/Select_tonkho_theosanpham", ReplyAction="http://tempuri.org/IServiceTonKho/Select_tonkho_theosanphamResponse")]
        giayit.ServiceReferenceTonKho.tonkho[] Select_tonkho_theosanpham(System.DateTime ngay, string masp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTonKho/Select_tonkho_theosanpham", ReplyAction="http://tempuri.org/IServiceTonKho/Select_tonkho_theosanphamResponse")]
        System.Threading.Tasks.Task<giayit.ServiceReferenceTonKho.tonkho[]> Select_tonkho_theosanphamAsync(System.DateTime ngay, string masp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTonKho/Themtk", ReplyAction="http://tempuri.org/IServiceTonKho/ThemtkResponse")]
        bool Themtk(string masp, int soluong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTonKho/Themtk", ReplyAction="http://tempuri.org/IServiceTonKho/ThemtkResponse")]
        System.Threading.Tasks.Task<bool> ThemtkAsync(string masp, int soluong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTonKho/giamtk", ReplyAction="http://tempuri.org/IServiceTonKho/giamtkResponse")]
        bool giamtk(string masp, int soluong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTonKho/giamtk", ReplyAction="http://tempuri.org/IServiceTonKho/giamtkResponse")]
        System.Threading.Tasks.Task<bool> giamtkAsync(string masp, int soluong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTonKho/Trusoluongkhidathang", ReplyAction="http://tempuri.org/IServiceTonKho/TrusoluongkhidathangResponse")]
        bool Trusoluongkhidathang(string mahd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTonKho/Trusoluongkhidathang", ReplyAction="http://tempuri.org/IServiceTonKho/TrusoluongkhidathangResponse")]
        System.Threading.Tasks.Task<bool> TrusoluongkhidathangAsync(string mahd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTonKho/Them", ReplyAction="http://tempuri.org/IServiceTonKho/ThemResponse")]
        bool Them(string masp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTonKho/Them", ReplyAction="http://tempuri.org/IServiceTonKho/ThemResponse")]
        System.Threading.Tasks.Task<bool> ThemAsync(string masp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceTonKhoChannel : giayit.ServiceReferenceTonKho.IServiceTonKho, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceTonKhoClient : System.ServiceModel.ClientBase<giayit.ServiceReferenceTonKho.IServiceTonKho>, giayit.ServiceReferenceTonKho.IServiceTonKho {
        
        public ServiceTonKhoClient() {
        }
        
        public ServiceTonKhoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceTonKhoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTonKhoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTonKhoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public giayit.ServiceReferenceTonKho.tonkho[] getalltonkho() {
            return base.Channel.getalltonkho();
        }
        
        public System.Threading.Tasks.Task<giayit.ServiceReferenceTonKho.tonkho[]> getalltonkhoAsync() {
            return base.Channel.getalltonkhoAsync();
        }
        
        public giayit.ServiceReferenceTonKho.tonkho[] getalltonkholoc(System.DateTime time) {
            return base.Channel.getalltonkholoc(time);
        }
        
        public System.Threading.Tasks.Task<giayit.ServiceReferenceTonKho.tonkho[]> getalltonkholocAsync(System.DateTime time) {
            return base.Channel.getalltonkholocAsync(time);
        }
        
        public giayit.ServiceReferenceTonKho.tonkho[] Select_tonkho(System.DateTime ngay, string maloai) {
            return base.Channel.Select_tonkho(ngay, maloai);
        }
        
        public System.Threading.Tasks.Task<giayit.ServiceReferenceTonKho.tonkho[]> Select_tonkhoAsync(System.DateTime ngay, string maloai) {
            return base.Channel.Select_tonkhoAsync(ngay, maloai);
        }
        
        public giayit.ServiceReferenceTonKho.tonkho[] Select_tonkho_theosanpham(System.DateTime ngay, string masp) {
            return base.Channel.Select_tonkho_theosanpham(ngay, masp);
        }
        
        public System.Threading.Tasks.Task<giayit.ServiceReferenceTonKho.tonkho[]> Select_tonkho_theosanphamAsync(System.DateTime ngay, string masp) {
            return base.Channel.Select_tonkho_theosanphamAsync(ngay, masp);
        }
        
        public bool Themtk(string masp, int soluong) {
            return base.Channel.Themtk(masp, soluong);
        }
        
        public System.Threading.Tasks.Task<bool> ThemtkAsync(string masp, int soluong) {
            return base.Channel.ThemtkAsync(masp, soluong);
        }
        
        public bool giamtk(string masp, int soluong) {
            return base.Channel.giamtk(masp, soluong);
        }
        
        public System.Threading.Tasks.Task<bool> giamtkAsync(string masp, int soluong) {
            return base.Channel.giamtkAsync(masp, soluong);
        }
        
        public bool Trusoluongkhidathang(string mahd) {
            return base.Channel.Trusoluongkhidathang(mahd);
        }
        
        public System.Threading.Tasks.Task<bool> TrusoluongkhidathangAsync(string mahd) {
            return base.Channel.TrusoluongkhidathangAsync(mahd);
        }
        
        public bool Them(string masp) {
            return base.Channel.Them(masp);
        }
        
        public System.Threading.Tasks.Task<bool> ThemAsync(string masp) {
            return base.Channel.ThemAsync(masp);
        }
    }
}
