//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceGiayit
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class giayitEntities : DbContext
    {
        public giayitEntities()
            : base("name=giayitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<admin> admins { get; set; }
        public DbSet<chitiethoadon> chitiethoadons { get; set; }
        public DbSet<chitietphieunhap> chitietphieunhaps { get; set; }
        public DbSet<hoadon> hoadons { get; set; }
        public DbSet<loaisanpham> loaisanphams { get; set; }
        public DbSet<nhacungcap> nhacungcaps { get; set; }
        public DbSet<phanquyen> phanquyens { get; set; }
        public DbSet<phieunhap> phieunhaps { get; set; }
        public DbSet<sanpham> sanphams { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<tintuc> tintucs { get; set; }
        public DbSet<tonkho> tonkhoes { get; set; }
        public DbSet<user> users { get; set; }
    }
}
