//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceGiayit
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoadon
    {
        public hoadon()
        {
            this.chitiethoadons = new HashSet<chitiethoadon>();
        }
    
        public int mahoadon { get; set; }
        public string makhachhang { get; set; }
        public string tenkhachhang { get; set; }
        public string diachi { get; set; }
        public string email { get; set; }
        public string sdt { get; set; }
        public Nullable<int> tongtien { get; set; }
        public Nullable<System.DateTime> ngaymuahang { get; set; }
        public Nullable<System.DateTime> ngaygiaohang { get; set; }
        public string tinhtrang { get; set; }
        public string ghichu { get; set; }
    
        public virtual ICollection<chitiethoadon> chitiethoadons { get; set; }
        public virtual user user { get; set; }
    }
}
