//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceGiayit
{
    using System;
    using System.Collections.Generic;
    
    public partial class tonkho
    {
        public System.DateTime ngay { get; set; }
        public string masanpham { get; set; }
        public Nullable<int> soluong { get; set; }
    }
}
