//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceGiayit
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.hoadons = new HashSet<hoadon>();
        }
    
        public string makhachhang { get; set; }
        public string tenkhachhang { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public Nullable<int> gioitinh { get; set; }
        public string sdt { get; set; }
        public string diachi { get; set; }
        public string email { get; set; }
        public Nullable<int> maphanquyen { get; set; }
        public string ghichu { get; set; }
    
        public virtual ICollection<hoadon> hoadons { get; set; }
        public virtual phanquyen phanquyen { get; set; }
    }
}
